### ISSUE TITLE
Не покрашено много вещей

### ISSUE THREAD

**Issue by jAba65** [ProChopa/ProDiscord#1]
![image](https://github.com/ProChopa/ProDiscord/assets/103503396/5812644f-57af-4230-8996-03452f16cc87)
![image_per50_per50](https://github.com/ProChopa/ProDiscord/assets/103503396/63b14591-9320-4c96-a31d-ad048944f54f)
![image](https://github.com/ProChopa/ProDiscord/assets/103503396/712b6400-8cd5-46c2-bb1f-f3412f2192b0)
![image](https://github.com/ProChopa/ProDiscord/assets/103503396/62ecfafd-b3ed-409d-b4b8-0b11f0f46860)

**Comment by ProChopa** [comment]
Привет, спасибо, всё вижу, знаю про все косяки темы, ежедневно слежу за своими темами и если что-то ломается, то при ближайшем свободном времени всё исправляю. К тому же прям ВСЁ я физически не могу покрасить, нету столько времени. Самое основное покрашено. Какую бы тему я не посмотрел на просторах, везде есть "недокрасы". У меня чуть ли не самая идеальная в этом плане. К тому же Discord постоянно меняет свой код. Насколько могу успевать за ними, так и успеваю. ProDiscord не единственная тема, над которой я работаю. Так что всему своё время )

На первом скрине всё правильно покрашено. Кнопка завершения звонка не активна, поэтому она не синяя, а просто серая. На остальных скринах, как и написал выше, код сменился, поэтому всё и поплыло.

**Comment by jAba65** [comment]
Всё ясно, спасибо удачи
